{
 "title": "Snyk / hash-lookup",
 "tags": [ "snyk" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": "label_values(http_request_duration_seconds_bucket{job=\"$service_name\"}, path)"
   },
   { "name": "service_name", "label": "service_name", "query": "hash-lookup" },
   { "name": "percentile", "label": "percentile", "query": "99,95,50" }
  ]
 },
 "panels": [
  {
   "title": "Latency: Quantile of HTTP request duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentile, sum(rate(http_request_duration_seconds_bucket{job=\"$service_name\"}[5m])) by (le, path))\n",
     "legendFormat": "${percentile}th: {{path}} "
    }
   ]
  },
  {
   "title": "Traffic: Rate of 200",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$service_name\",path=\"$endpoint\",status_code=\"200\"}[5m]))",
     "legendFormat": "$endpoint"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$service_name\",status_code=\"200\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Traffic: Global RPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$service_name\",path=\"$endpoint\"}[5m]))",
     "legendFormat": "$endpoint"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$service_name\"}[5m]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Errors: % of 500",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$service_name\",path=\"$endpoint\",status_code=\"500\"}[5m]))/sum(rate(http_requests_total{job=\"$service_name\",path=\"$endpoint\"}[5m]))",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Traffic: Rate of 500",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$service_name\",path=\"$endpoint\",path=\"500\"}[5m]))",
     "legendFormat": "$endpoint"
    }
   ]
  },
  {
   "title": "Saturation: System memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$service_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Saturation: CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$service_name\"}[1m])*100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Saturation: Active handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nodejs_active_handles_total{job=\"$service_name\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Saturation: File descriptor leak",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(process_open_fds{job=\"$service_name\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Saturation: File descriptor usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"$service_name\"}/process_max_fds{job=\"$service_name\"} *100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Saturation: Event loop lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=\"$service_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Saturation: Active requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(nodejs_active_requests_total{job=\"$service_name\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Saturation: Heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_heap_bytes{job=\"$service_name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}